name: note_app_riv
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
